sudo: false

matrix:
  include:
    - os: linux
      PYTHON_VERSION: 2.7
    - os: linux
      PYTHON_VERSION: 3.4
    - os: osx
      PYTHON_VERSION: 2.7
    - os: osx
      PYTHON_VERSION: 3.4

install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      if [[ "$PYTHON_VERSION" == "2.7" ]]; then
        wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
      else
        wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      fi
    else
      if [[ "$PYTHON_VERSION" == "2.7" ]]; then
        wget https://repo.continuum.io/miniconda/Miniconda-latest-MacOSX-x86_64.sh -O miniconda.sh;
      else
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
      fi
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes
  - conda update -q conda
  - conda info -a
  - conda install numpy cython pytest
  - python setup.py install
  # Build and Upload help
  - pip install -r .ci/requirements.txt

script:
  - export PATH="$(pwd)/bin:$PATH"
  - echo $PATH
  # Download test Data
  - mkdir -p $HOME/data
  - pushd $HOME/data
  - wget http://mattmahoney.net/dc/text8.zip -O text8.zip
  - unzip text8.zip
  - head -c 1000000 text8 > text
  - popd
  # py.test
  - pushd word2vec/tests
  - py.test -s -vv
  - popd
  # Build
  - python setup.py bdist_wheel
  - ls dist
  # Upload
  - aws s3 cp dist/*whl s3://danielfrg-ci/word2vec/
