version: "{build}"

os: Windows Server 2012 R2

environment:
  matrix:
    - PYTHON_VERSION: "2.7.10"
      MINICONDA: C:\Miniconda
    - PYTHON_VERSION: "3.5.1"
      MINICONDA: C:\Miniconda3

branches:
  only:
    - master

clone_folder: c:\workspace\word2vec

install:
  - "set PATH=C:\\MinGW\\bin;%PATH%"
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
  - echo %PATH%
  - conda config --set always_yes yes
  - conda update -q conda
  - conda info -a

build_script:
  - conda install --file .ci/conda-requirements.txt -y -q
  - pip install -r .ci/requirements.txt
  - python setup.py bdist_wheel
  - ls dist
  - "pip install --pre --no-index --find-links dist/ word2vec"

# test_script: # TODO

on_success:
  - cd dist
  - if not defined APPVEYOR_PULL_REQUEST_NUMBER (
      aws s3 cp . s3://danielfrg-ci/word2vec/ --recursive --exclude * --include *.wh
    ) else (
      echo "Pull Request -> No upload"
    )
