version: "{build}"

os: Windows Server 2012 R2

environment:
  global:
    CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\.ci\\run_with_env.cmd"
    AWS_ACCESS_KEY_ID:
      secure: xalXUrYrSfaJPK9k7rn0CrdmTK/2WcZzHP28wXD+VvM=
    AWS_SECRET_ACCESS_KEY:
      secure: DDabqC3dvAnpkUXK5+r/htaVvV4wPonAWF9iBC6K4WMtUrDZJm5EUQ+SBPxOQAW8

  matrix:
    - PYTHON_VERSION: "2.7.10"
      MINICONDA: C:\Miniconda
      PYTHON_ARCH: "64"
    - PYTHON_VERSION: "3.5.1"
      MINICONDA: C:\Miniconda3
      PYTHON_ARCH: "64"


clone_folder: c:\workspace\word2vec

# Not a .NET project building on test_script
build: false

install:
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
  - conda config --set always_yes yes
  - conda update -q conda
  - conda install -y -q pip
  - conda info -a
  # Build
  - conda install --file .ci/conda-requirements.txt -y
  - python setup.py bdist_wheel
  - ls dist
  - pip install dist/*.whl

# test_script:

after_test:
  - pip install -r .ci/requirements.txt
  - aws s3 cp dist/*.whl s3://danielfrg-ci/word2vec/
